# Generated by Django 5.2.3 on 2025-06-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityclasses',
            options={'verbose_name': 'University Class', 'verbose_name_plural': 'University Classes'},
        ),
    ]
