# Generated by Django 5.2.3 on 2025-06-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('campus_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'University Campus',
                'verbose_name_plural': 'University Campuses',
            },
        ),
    ]
